import { Box } from '@mui/material'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Layout from '../components/Layout'
import MainPage from '../components/main';

export default function Home() {
  const [user, setUser] = useState({
    isLogin: false,
    user: []
  });

  useEffect(() => {
    fetchUser();
  }, [])

  const fetchUser = () => {
    try {
        const login = JSON.parse(localStorage.login)
        setUser(login)
    } catch (error) {
        return ''           
    }
}

  return (
    <Box>
        <Head>
          <title>Information Retrieval Pencarian Jurnal</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
            <Layout judulmenu={`Selamat Datang ${user.isLogin ? user.user.nama : "User" } `}>
              {user.isLogin 
                ?
                <MainPage user={user} />
                : ''
              }
            </Layout>

      </Box>
  )
}